[package]
name = "cli"
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
bip39 = { workspace = true, features = ["rand"] }
bitcoin.workspace = true
breez-sdk-core.workspace = true
clap = { workspace = true, features = ["derive"] }
dirs = "6.0.0"
rustyline = { workspace = true, features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
shlex = "1.3.0"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing.workspace = true

[lints]
workspace = true
