[workspace]
resolver = "2"

members = ["crates/spark", "crates/spark-protos", "crates/spark-wallet"]

[workspace.dependencies]
async-trait = "0.1.88"
bip32 = "0.5.3"
bitcoin = "0.32.6"
frost-core = "2.1.0"
frost-secp256k1-tr = "2.1.0"
hex = "0.4.3"
prost = "0.13.4"
prost-types = "0.13.4"
serde = "1.0.219"
serde_json = "1.0.140"
spark-protos = { path = "crates/spark-protos" }
spark = { path = "crates/spark" }
spark-wallet = { path = "crates/spark-wallet" }
thiserror = "2.0.12"
tokio = { version = "1.45.1", default-features = false }
tonic = { version = "0.12.3", features = [
    "tls",
    "tls-native-roots",
    "prost",
    "channel",
] }
tonic-build = { version = "0.12.3", features = ["prost"] }
tracing = "0.1.41"
uuid = { version = "1.17.0", features = ["v7"] }
