[package]
name = "breez-sdk-core"
edition = "2024"
version.workspace = true

[dependencies]
bip39.workspace = true
bitcoin.workspace = true
breez-sdk-common.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
dotenvy.workspace = true
figment = { workspace = true, features = ["env", "yaml"] }
hex.workspace = true
qrcode-rs.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
rusqlite_migration.workspace = true
rustyline = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
shellwords.workspace = true
spark-wallet.workspace = true
tempdir.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid.workspace = true
breez-sdk-macros.workspace = true
async-trait.workspace = true
esplora-client = "0.12.1"

[dev-dependencies]
mockito = "1.2.0"
