[package]
name = "spark"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
base64.workspace = true
bitcoin = { workspace = true, features = ["rand"] }
chrono = { workspace = true, features = ["serde"] }
ecies.workspace = true
enum_to_enum.workspace = true
frost-core.workspace = true
frost-secp256k1-tr.workspace = true
futures.workspace = true
graphql_client.workspace = true
hex.workspace = true
k256 = { workspace = true, features = ["arithmetic", "schnorr", "ecdsa"] }
lightning-invoice.workspace = true
prost.workspace = true
prost-types.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["json"] }
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
spark-macros.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tonic.workspace=true
tracing.workspace = true
uuid.workspace = true

[build-dependencies]
tonic.workspace = true
tonic-build.workspace = true
