[package]
name = "spark"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
bip32 = "0.5.3"
bitcoin = "0.32.6"
prost = "0.14.0"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tonic = "0.13.1"
uuid = { version = "1.17.0", features = ["v7"] }

[build-dependencies]
prost-build = "0.14.0"
tonic-build = "0.13.1"
