[package]
name = "spark"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
bip32 = "0.5.3"
bitcoin = "0.32.6"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tonic.workspace = true
uuid = { version = "1.17.0", features = ["v7"] }
log = "0.4.27"
spark-protos = { workspace = true }
