[package]
name = "spark"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
base64.workspace = true
bip32.workspace = true
bitcoin = { workspace = true, features = ["rand"] }
chrono = { workspace = true, features = ["serde"] }
frost-core.workspace = true
frost-secp256k1-tr.workspace = true
hex.workspace = true
prost.workspace = true
reqwest = { workspace = true, features = ["json"] }
rustls = { version = "0.23.28", features = ["ring"] }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tonic.workspace = true
tracing.workspace = true
uuid.workspace = true
lightning-invoice.workspace = true
prost-types.workspace = true

[build-dependencies]
tonic.workspace = true
tonic-build.workspace = true