[package]
name = "spark"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
bip32 = "0.5.3"
bitcoin.workspace = true
serde = "1.0.219"
serde_json = "1.0.140"
thiserror.workspace = true
tonic.workspace = true
uuid.workspace = true
log = "0.4.27"
spark-protos = { workspace = true }
