[package]
name = "spark"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
bip32.workspace = true
bitcoin.workspace = true
serde.workspace = true
serde_json.workspace = true
spark-protos.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tonic.workspace = true
tracing.workspace = true
uuid.workspace = true
