[package]
name = "spark-protos"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
tonic.workspace = true
tonic-build.workspace = true