[package]
name = "breez-sdk-spark-flutter"
version = "0.1.4"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
async-trait.workspace = true
breez-sdk-common.workspace = true
breez-sdk-spark.workspace = true
extend = "1.2.0"
flutter_rust_bridge = "=2.11.1"

[build-dependencies]
flutter_rust_bridge_codegen = "=2.11.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
