[package]
name = "breez-sdk-spark-flutter"
version = "0.1.3"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
async-trait = "0.1.88"
# Replaced with release commit during publishing
breez-sdk-common = { path = "../../../crates/breez-sdk/common" }
breez-sdk-spark = { path = "../../../crates/breez-sdk/core" }
extend = "1.2.0"
flutter_rust_bridge = "=2.11.1"

[build-dependencies]
flutter_rust_bridge_codegen = "=2.11.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
