name: Publish Flutter Bindings
on:
  workflow_call:
    inputs:
      repository:
        description: 'SDK repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'Git commit, tag or branch reference'
        required: true
        type: string
      package-version:
        description: 'Version for the gradle library (MAJOR.MINOR.BUILD)'
        required: true
        type: string
      publish:
        description: 'Should publish'
        required: true
        type: boolean
        default: false
    secrets:
      REPO_SSH_KEY:
        description: 'SSH key to commit to the breez-sdk-spark-flutter repository'
        required: true
      FLUTTER_RELEASE_TOKEN:
        description: 'GitHub token to release to the breez-sdk-spark-flutter repository'
        required: true
      CARGOKIT_PRIVATE_KEY:
        description: 'Cargokit private key for signing precompiled binaries'
        required: true

jobs:
  build-package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}

      - name: Checkout breez-sdk-spark-flutter repo
        uses: actions/checkout@v4
        with:
          repository: breez/breez-sdk-spark-flutter
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          fetch-depth: 0
          path: dist
  
      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0

      - name: Set cargo version
        working-directory: packages/flutter/rust
        run: |
          sed -i.bak -e 's/^breez-sdk-common = .*/breez-sdk-common = { git = "https:\/\/github.com\/breez\/spark-sdk.git", rev = "${{ github.sha }}" }/' Cargo.toml
          sed -i.bak -e 's/^breez-sdk-spark = .*/breez-sdk-spark = { git = "https:\/\/github.com\/breez\/spark-sdk.git", rev = "${{ github.sha }}", features = ["openssl-vendored"] }/' Cargo.toml
          rm Cargo.toml.bak

      - name: Generate bindings
        working-directory: packages/flutter
        run: make generate-bindings-build-release
  
      - name: Copy package files
        working-directory: dist
        run: |
          rm -rf android ios macos lib rust
          cp -r ../packages/flutter/android .
          cp -r ../packages/flutter/ios .
          cp -r ../packages/flutter/macos .
          cp -r ../packages/flutter/lib .
          cp -r ../packages/flutter/rust .
          rm lib/src/.gitignore rust/src/.gitignore
          rm -rf rust/target
          cp ../packages/flutter/*.yaml .
          cp ../packages/flutter/README.md .

      - name: Set package version
        working-directory: dist
        run: |
          sed -i.bak -e 's/version:.*/version: ${{ inputs.package-version }}/' pubspec.yaml
          sed -i.bak -e "s/^version .*/version '${{ inputs.package-version }}'/" android/build.gradle
          sed -i.bak -e "s/^version = .*/version = '${{ inputs.package-version }}'/" ios/breez_sdk_spark.podspec
          sed -i.bak -e "s/^version = .*/version = '${{ inputs.package-version }}'/" macos/breez_sdk_spark.podspec
          rm pubspec.yaml.bak android/build.gradle.bak
          rm ios/breez_sdk_spark.podspec.bak macos/breez_sdk_spark.podspec.bak

      - name: Archive package
        if: ${{ !inputs.publish }}
        uses: actions/upload-artifact@v4
        with:
          name: flutter-${{ inputs.package-version || '0.0.2' }}
          path: dist/*

      - name: Tag the Flutter package
        working-directory: dist
        if: ${{ inputs.publish }}
        run: |
          git config --global user.name "SDK release tagger"
          git config --global user.email "no-reply@breez.technology"
          git add .
          git commit -m "Update Flutter package to version v${{ inputs.package-version }}"
          git push
          git tag v${{ inputs.package-version }} -m "v${{ inputs.package-version }}"
          git push --tags

  precompile-binaries:
    name: Precompile binaries ${{ matrix.os }}
    needs: build-package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
          macOS-latest,
        ]
    steps:
      - name: Checkout breez-sdk-spark-flutter repo
        uses: actions/checkout@v4
        with:
          repository: breez/breez-sdk-spark-flutter
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          fetch-depth: 0
  
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "30.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install GTK
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
      
      - name: Setup Android SDK
        if: matrix.os == 'ubuntu-latest'
        uses: android-actions/setup-android@v3

      - name: Install NDK
        if: matrix.os == 'ubuntu-latest'
        run: sdkmanager "ndk;23.2.8568313"

      - name: Set IPHONEOS_DEPLOYMENT_TARGET
        if: matrix.os == 'macOS-latest'
        run: echo "IPHONEOS_DEPLOYMENT_TARGET=13.0" >> $GITHUB_ENV

      - name: Precompile ${{ matrix.os }}
        if: inputs.publish && matrix.os == 'macOS-latest'
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=breez/breez-sdk-spark-flutter
        working-directory: cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.FLUTTER_RELEASE_TOKEN }}
          PRIVATE_KEY: ${{ secrets.CARGOKIT_PRIVATE_KEY }}

      - name: Precompile ${{ matrix.os }}
        if: inputs.publish && matrix.os == 'ubuntu-latest'
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=breez/breez-sdk-spark-flutter --android-sdk-location=$ANDROID_HOME --android-ndk-version=23.2.8568313 --android-min-sdk-version=24
        working-directory: cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.FLUTTER_RELEASE_TOKEN }}
          PRIVATE_KEY: ${{ secrets.CARGOKIT_PRIVATE_KEY }}
