name: Publish Go Bindings
on:
  workflow_call:
    inputs:
      repository:
        description: 'SDK repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'Git commit, tag or branch reference'
        required: true
        type: string
      package-version:
        description: 'Version for the python package (MAJOR.MINOR.BUILD)'
        required: true
        type: string
      publish:
        description: 'Should publish to breez-sdk-spark-go'
        required: true
        type: boolean
        default: false
    secrets:
      REPO_SSH_KEY:
        description: 'SSH key to commit to the breez-sdk-spark-go repository'
        required: true

jobs:
  build-language-bindings:
    name: Build language bindings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}
  
      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download aarch64-linux-android
        uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-linux-android
          path: aarch64-linux-android

      - name: Build Go language bindings
        working-directory: crates/breez-sdk/bindings
        run: |
          cargo install uniffi-bindgen-go --git https://github.com/breez/uniffi-bindgen-go --rev 8b8c58f78b2dc16a252f325da91ce409f409fe3c
          uniffi-bindgen-go --library ../../../aarch64-linux-android/libbreez_sdk_spark_bindings.so -o ffi/golang -c ./uniffi.toml

      - name: Archive Go language bindings
        uses: actions/upload-artifact@v4
        with:
          name: bindings-golang
          path: crates/breez-sdk/bindings/ffi/golang

  build-package:
    name: Build package
    runs-on: ubuntu-latest
    needs: build-language-bindings
    steps:
      - name: Checkout breez-sdk-spark-go repo
        uses: actions/checkout@v4
        with:
          repository: breez/breez-sdk-spark-go
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: bindings-golang

      - uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-linux-android
          path: breez_sdk_spark/lib/android-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: bindings-i686-linux-android
          path: breez_sdk_spark/lib/android-386

      - uses: actions/download-artifact@v4
        with:
          name: bindings-armv7-linux-androideabi
          path: breez_sdk_spark/lib/android-aarch

      - uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-linux-android
          path: breez_sdk_spark/lib/android-amd64

      - uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-apple-darwin
          path: breez_sdk_spark/lib/darwin-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-apple-darwin
          path: breez_sdk_spark/lib/darwin-amd64

      - uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-unknown-linux-gnu
          path: breez_sdk_spark/lib/linux-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-unknown-linux-gnu
          path: breez_sdk_spark/lib/linux-amd64

      - uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-pc-windows-msvc
          path: breez_sdk_spark/lib/windows-amd64
  
      - name: Remove static libs
        working-directory: breez_sdk_spark/lib
        run: rm -rf **/*.a

      - name: Archive package
        if: ${{ !inputs.publish }}
        uses: actions/upload-artifact@v4
        with:
          name: golang-${{ inputs.package-version || github.sha }}
          path: |
            ./*
            !./.git

      - name: Tag the Go package
        if: ${{ inputs.publish }}
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git add .
          git commit -m "Update Go bindings to version v${{ inputs.package-version }}"
          git push
          git tag v${{ inputs.package-version }} -m "v${{ inputs.package-version }}"
          git push --tags
