# Kotlin https://gobley.dev/docs/bindgen#bindgen-configuration
package_name = "breez_sdk_spark.bindings"
cdylib_name = "breez_sdk_spark_bindings"
kotlin_multiplatform = false
kotlin_targets = ["jvm"]
kotlin_target_version = "1.9.21"
disable_java_cleaner = true

# https://mozilla.github.io/uniffi-rs/swift/configuration.html
[bindings.swift]
ffi_module_name = "breez_sdk_sparkFFI"
ffi_module_filename = "breez_sdk_spark_bindingsFFI"
cdylib_name = "breez_sdk_spark_bindings"

# https://mozilla.github.io/uniffi-rs/python/configuration.html
[bindings.python]
cdylib_name = "breez_sdk_spark_bindings"

[bindings.python.external_packages]
# This fixture does not create a Python package, so we want all modules to be top-level modules.
breez_sdk_core = ""

# https://github.com/NordSecurity/uniffi-bindgen-cs/blob/main/docs/CONFIGURATION.md
[bindings.csharp]
package_name = "breez_sdk_spark"
cdylib_name = "breez_sdk_spark_bindings"
namespace = "Breez.Sdk.Spark"
access_modifier = "public"

# https://github.com/NordSecurity/uniffi-bindgen-go/blob/main/docs/CONFIGURATION.md
[bindings.go]
package_name = "breez_sdk_spark"
cdylib_name = "breez_sdk_spark_bindings"
