[package]
name = "spark-wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true, features = ["serde"] }
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
spark.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }
uuid.workspace = true